config {
  type: "operations",
  dependencies: ["fct_product"],
  tags: ["None", "product", "archive"]
}

INSERT INTO `sentinel-486707.sentinel_raw.product_raw_hist` (
  product_id,
  product_name,
  category,
  base_price,
  batch_date, 
  processed_dttm
)
SELECT
  product_id,
  product_name,
  category,
  base_price,
  CURRENT_DATE() AS batch_date,
  SAFE_CAST(processed_dttm AS TIMESTAMP) AS processed_dttm
FROM ${ref("product_raw")};

TRUNCATE TABLE ${ref("product_raw")};