project_id                       = "sentinel-486707"
region                           = "us-central1"
ingestion_landing_bucket_name    = "sentinel-ingestion-landing"
ingestion_archive_bucket_name    = "sentinel-ingestion-archive"
code_bucket_name                 = "sentinel-ingestor-code"
github_token                     = "dfkyujnm"
repo_name                        = "Vijayrajdev/sentinel"
pubsub_topic                     = "schema-drift-events"