config {
  type: "operations",
  dependencies: ["fct_product"],
  tags: ["sales", "product", "archive"]
}

INSERT INTO `sentinel-486707.sentinel_raw.product_raw_hist` (
  product_id,
  product_name,
  category,
  base_price,
  batch_date,
  processed_dttm,
  archive_batch_date
)
SELECT
  product_id,
  product_name,
  category,
  base_price,
  batch_date,
  processed_dttm,
  CURRENT_DATE() AS archive_batch_date
FROM
  ${ref("product_raw")};

TRUNCATE TABLE ${ref("product_raw")};
