config {
  type: "operations",
  schema: "sentinel_raw",
  tags: ["ecommerce", "product", "archive"]
}

INSERT INTO `sentinel-486707.sentinel_raw.product_raw_hist` (
    product_id,
    product_name,
    category,
    base_price,
    batch_date,
    processed_dttm
)
SELECT
    product_id,
    product_name,
    category,
    base_price,
    CURRENT_DATE() AS batch_date,
    processed_dttm
FROM `sentinel-486707.sentinel_raw.product_raw`;

TRUNCATE TABLE `sentinel-486707.sentinel_raw.product_raw`;