config {
  type: "view",
  schema: "sentinel_staging",
  name: "stg_orders",
  tags: ["staging", "sales"],
  description: "Staging model for orders. Performs cleaning, casting, and renaming of raw orders data."
}

SELECT
  order_id,
  customer_name,
  SAFE_CAST(amount AS FLOAT64) AS amount,
  status,
  SAFE.PARSE_DATE('%Y-%m-%d', order_date) AS order_date,
  product_id,
  email,
  warehouse_id,
  processed_dttm
FROM
  ${ref("orders_raw")}